"""Reports API — Case report PDF (confirmed only) + BSA §63 certificate."""
from uuid import UUID
import tempfile
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.database import get_db
from app.models.case import Case
from app.models.lead import Lead
from app.models.evidence import Evidence, CustodyLog
from app.models.user import User
from app.core.security import get_current_user
from app.core.custody import write_custody

router = APIRouter(tags=["Reports"])


@router.get("/cases/{case_id}/report")
async def generate_case_report(
    case_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Case report PDF — confirmed findings ONLY."""
    case_result = await db.execute(select(Case).where(Case.id == case_id))
    case = case_result.scalar_one_or_none()
    if not case:
        raise HTTPException(404, "Case not found")

    leads_result = await db.execute(
        select(Lead).where(Lead.case_id == case_id, Lead.status == "confirmed")
    )
    confirmed_leads = leads_result.scalars().all()

    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(14, 17, 22)
    pdf.cell(0, 12, "ACPIA — Case Investigation Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(125, 137, 152)
    pdf.cell(0, 5, "POLICE INTELLIGENCE DOCUMENT — RESTRICTED", ln=True, align="C")
    pdf.cell(0, 5, "Contains confirmed findings only. AI-proposed leads are excluded.", ln=True, align="C")
    pdf.ln(8)

    # Case info
    pdf.set_font("Courier", "B", 12)
    pdf.set_text_color(214, 222, 232)
    pdf.set_fill_color(22, 27, 34)
    pdf.cell(0, 8, f"  {case.reference} — {case.title}", ln=True, fill=True)
    pdf.set_font("Courier", "", 10)
    pdf.set_text_color(125, 137, 152)
    pdf.cell(0, 6, f"  Status: {case.status} | Generated: {datetime.now(timezone.utc).isoformat()}", ln=True)
    pdf.cell(0, 6, f"  Generated by: {current_user.username} (role: {current_user.role})", ln=True)
    pdf.ln(6)

    # Confirmed findings
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(74, 127, 165)
    pdf.cell(0, 8, f"Confirmed Findings ({len(confirmed_leads)})", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    if not confirmed_leads:
        pdf.set_font("Helvetica", "I", 11)
        pdf.set_text_color(78, 88, 101)
        pdf.cell(0, 8, "No confirmed findings in this case.", ln=True)
    else:
        for i, lead in enumerate(confirmed_leads, 1):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(214, 222, 232)
            pdf.cell(0, 7, f"{i}. {lead.kind.replace('_', ' ').upper()}", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(214, 222, 232)
            pdf.multi_cell(0, 6, lead.summary)
            pdf.set_font("Courier", "", 9)
            pdf.set_text_color(78, 88, 101)
            pdf.cell(0, 5, f"Confidence: {float(lead.confidence):.2f} ± {float(lead.confidence_ci):.2f}", ln=True)
            pdf.cell(0, 5, f"Confirmed: {lead.judged_at.isoformat() if lead.judged_at else 'N/A'}", ln=True)
            pdf.cell(0, 5, f"Sources: {len(lead.source_ids)} evidence item(s) cited", ln=True)
            pdf.ln(4)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(78, 88, 101)
    pdf.multi_cell(0, 5,
        "This report contains only findings confirmed by an authorised investigator. "
        "AI-generated leads excluded by design. See BSA §63 certificate for full chain of custody."
    )

    await write_custody(
        db, case_id, current_user.id,
        action="REPORT_GENERATED",
        target_type="case",
        target_id=case_id,
        detail={"confirmed_leads": len(confirmed_leads)},
    )
    await db.commit()

    pdf_bytes = bytes(pdf.output())
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    tmp.write(pdf_bytes)
    tmp.close()
    return FileResponse(tmp.name, media_type="application/pdf",
                        filename=f"ACPIA-Report-{case.reference}.pdf")


@router.get("/cases/{case_id}/certificate")
async def generate_bsa_certificate(
    case_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """BSA §63 certificate — every hash, full custody log, dual signature blocks."""
    case_result = await db.execute(select(Case).where(Case.id == case_id))
    case = case_result.scalar_one_or_none()
    if not case:
        raise HTTPException(404, "Case not found")

    evs_result = await db.execute(
        select(Evidence).where(Evidence.case_id == case_id).order_by(Evidence.created_at)
    )
    evidence_list = evs_result.scalars().all()

    custody_result = await db.execute(
        select(CustodyLog).where(CustodyLog.case_id == case_id).order_by(CustodyLog.at)
    )
    custody_entries = custody_result.scalars().all()

    from fpdf import FPDF
    pdf = FPDF()
    pdf.add_page()

    # Certificate header
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(26, 36, 48)
    pdf.cell(0, 10, "CERTIFICATE OF ELECTRONIC EVIDENCE", ln=True, align="C")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Bharatiya Sakshya Adhiniyam 2023 — Section 63", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(86, 100, 111)
    pdf.cell(0, 5, "Produced by ACPIA — Agentic Child Protection Intelligence Architecture", ln=True, align="C")
    pdf.ln(8)

    # Case
    pdf.set_font("Courier", "B", 11)
    pdf.set_text_color(26, 36, 48)
    pdf.cell(0, 6, f"Case Reference: {case.reference}", ln=True)
    pdf.cell(0, 6, f"Case Title: {case.title}", ln=True)
    pdf.cell(0, 6, f"Certificate Generated: {datetime.now(timezone.utc).isoformat()}", ln=True)
    pdf.cell(0, 6, f"Issuing Officer: {current_user.username} ({current_user.role})", ln=True)
    pdf.ln(6)

    # Evidence hashes
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(26, 36, 48)
    pdf.cell(0, 7, f"Evidence Artifacts ({len(evidence_list)})", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    for ev in evidence_list:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 5, ev.filename, ln=True)
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(86, 100, 111)
        sha_groups = " ".join(ev.sha256[i:i+8] for i in range(0, 64, 8))
        pdf.cell(0, 4, f"SHA-256: {sha_groups}", ln=True)
        pdf.cell(0, 4, f"Size: {ev.size_bytes:,} bytes  |  Integrity: {'OK' if ev.integrity_ok else 'FAILED'}", ln=True)
        pdf.set_text_color(26, 36, 48)
        pdf.ln(2)

    # Custody log
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, f"Chain of Custody Log ({len(custody_entries)} entries)", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    for entry in custody_entries:
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(86, 100, 111)
        pdf.cell(0, 4,
            f"{entry.at.isoformat()} | {entry.action:25s} | {entry.target_type:10s}",
            ln=True
        )

    # Signature blocks
    pdf.ln(12)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(26, 36, 48)
    pdf.cell(0, 7, "Certification", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6,
        "I certify that the SHA-256 digest values listed above were computed by ACPIA software "
        "from digital evidence stored on systems under my custody, and that the chain of custody "
        "recorded above accurately reflects all access and actions taken in relation to this evidence."
    )
    pdf.ln(10)
    pdf.cell(90, 6, "Signature of Investigating Officer", border="B")
    pdf.cell(10)
    pdf.cell(90, 6, "Signature of Supervising Officer", border="B")
    pdf.ln(10)
    pdf.cell(90, 6, "Name: " + current_user.username)
    pdf.cell(10)
    pdf.cell(90, 6, "Name: ___________________")
    pdf.ln(8)
    pdf.cell(90, 6, "Date: " + datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    pdf.cell(10)
    pdf.cell(90, 6, "Date: ___________________")

    await write_custody(
        db, case_id, current_user.id,
        action="CERTIFICATE_GENERATED",
        target_type="case",
        target_id=case_id,
        detail={"evidence_count": len(evidence_list), "custody_entries": len(custody_entries)},
    )
    await db.commit()

    pdf_bytes = bytes(pdf.output())
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    tmp.write(pdf_bytes)
    tmp.close()
    return FileResponse(tmp.name, media_type="application/pdf",
                        filename=f"ACPIA-BSA63-Certificate-{case.reference}.pdf")
