"""
PDF Report Generation Endpoint
GET /api/v1/cases/{case_id}/report — generates a court-ready PDF report
"""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import io
import structlog
from datetime import datetime, timezone

from app.database import get_db
from app.auth.keycloak import get_current_user, CurrentUser
from app.models.models import Case, EvidenceItem, Lead, ChainOfCustodyLog

logger = structlog.get_logger(__name__)
router = APIRouter()


@router.get("/cases/{case_id}/report", tags=["Reports"])
async def generate_case_report(
    case_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Generate a comprehensive PDF investigation report for a case.
    Includes: case summary, all confirmed/pending leads, chain of custody, evidence index.
    """
    # Fetch case
    result = await db.execute(select(Case).where(Case.case_id == case_id))
    case = result.scalar_one_or_none()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")

    # Fetch evidence
    ev_result = await db.execute(
        select(EvidenceItem).where(EvidenceItem.case_id == case_id)
        .order_by(EvidenceItem.ingested_at)
    )
    evidence_items = ev_result.scalars().all()

    # Fetch leads (confirmed + pending)
    leads_result = await db.execute(
        select(Lead)
        .where(Lead.case_id == case_id)
        .order_by(Lead.risk_score.desc())
    )
    leads = leads_result.scalars().all()

    # Fetch custody log for first evidence item (for demo)
    custody_logs = []
    if evidence_items:
        coc_result = await db.execute(
            select(ChainOfCustodyLog)
            .where(ChainOfCustodyLog.evidence_id == evidence_items[0].evidence_id)
            .order_by(ChainOfCustodyLog.action_ts)
            .limit(20)
        )
        custody_logs = coc_result.scalars().all()

    # Generate PDF
    pdf_bytes = _generate_pdf(case, evidence_items, leads, custody_logs, current_user)

    filename = f"ACPIA_Report_{case.case_number}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-Case-ID": case_id,
            "X-Generated-By": current_user.username,
        }
    )


def _generate_pdf(case, evidence_items, leads, custody_logs, current_user) -> bytes:
    """Generate a styled PDF report using fpdf2."""
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────────────────────
    pdf.set_fill_color(15, 23, 42)      # dark slate
    pdf.rect(0, 0, 210, 30, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_y(8)
    pdf.cell(0, 10, "ACPIA — INTELLIGENCE INVESTIGATION REPORT", align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_y(20)
    pdf.cell(0, 6, "CONFIDENTIAL — LAW ENFORCEMENT USE ONLY", align="C")

    # ── Case Summary ─────────────────────────────────────────────────────────
    pdf.set_y(38)
    pdf.set_text_color(15, 23, 42)
    _section_header(pdf, "1. CASE SUMMARY")

    info_rows = [
        ("Case Number:", case.case_number),
        ("Title:", case.title),
        ("Status:", case.status.upper()),
        ("Priority:", case.priority.upper()),
        ("Jurisdiction:", case.jurisdiction),
        ("Opened:", str(case.opened_at)[:19] if case.opened_at else "—"),
        ("Evidence Items:", str(len(evidence_items))),
        ("Leads Generated:", str(len(leads))),
        ("Report Generated:", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")),
        ("Generated By:", current_user.full_name or current_user.username),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, value in info_rows:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 7, label)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, str(value)[:80], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    if case.description:
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 9)
        pdf.multi_cell(0, 5, case.description[:500])

    # ── Leads Summary ────────────────────────────────────────────────────────
    pdf.ln(5)
    _section_header(pdf, f"2. INVESTIGATIVE LEADS ({len(leads)} total)")

    if not leads:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 7, "No leads generated yet. Run the analysis pipeline first.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        # Table header
        pdf.set_fill_color(226, 232, 240)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(10, 7, "#", fill=True)
        pdf.cell(20, 7, "Risk", fill=True)
        pdf.cell(30, 7, "Status", fill=True)
        pdf.cell(40, 7, "Agent", fill=True)
        pdf.cell(0, 7, "Summary", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_font("Helvetica", "", 8)
        for i, lead in enumerate(leads[:30], 1):
            risk = float(lead.risk_score)
            if risk >= 70:
                pdf.set_text_color(185, 28, 28)
            elif risk >= 45:
                pdf.set_text_color(146, 64, 14)
            else:
                pdf.set_text_color(21, 128, 61)

            pdf.cell(10, 6, str(i))
            pdf.cell(20, 6, f"{risk:.0f}/100")
            pdf.set_text_color(15, 23, 42)
            pdf.cell(30, 6, lead.status.upper())
            pdf.cell(40, 6, (lead.generated_by_agent or "")[:20])
            pdf.cell(0, 6, (lead.summary or "")[:60], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            if lead.detailed_analysis:
                pdf.set_font("Helvetica", "I", 7)
                pdf.set_x(20)
                pdf.multi_cell(170, 4, lead.detailed_analysis[:200])
                pdf.set_font("Helvetica", "", 8)

    # ── Evidence Index ───────────────────────────────────────────────────────
    pdf.ln(5)
    _section_header(pdf, f"3. EVIDENCE INDEX ({len(evidence_items)} items)")

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(226, 232, 240)
    pdf.cell(10, 7, "#", fill=True)
    pdf.cell(80, 7, "Filename", fill=True)
    pdf.cell(40, 7, "Type", fill=True)
    pdf.cell(30, 7, "Status", fill=True)
    pdf.cell(0, 7, "SHA-256 (first 16)", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 8)
    for i, ev in enumerate(evidence_items[:50], 1):
        pdf.cell(10, 5, str(i))
        pdf.cell(80, 5, (ev.original_filename or "")[:40])
        pdf.cell(40, 5, (ev.mime_type or "")[:22])
        pdf.cell(30, 5, ev.processing_status or "—")
        pdf.cell(0, 5, (ev.sha256_hash or "")[:16] + "...", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Chain of Custody ─────────────────────────────────────────────────────
    if custody_logs:
        pdf.ln(5)
        _section_header(pdf, "4. CHAIN OF CUSTODY (Sample — First Evidence Item)")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(226, 232, 240)
        pdf.cell(50, 7, "Timestamp", fill=True)
        pdf.cell(50, 7, "Action", fill=True)
        pdf.cell(0, 7, "Hash", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_font("Helvetica", "", 8)
        for log in custody_logs:
            pdf.cell(50, 5, str(log.action_ts)[:19])
            pdf.cell(50, 5, log.action or "")
            pdf.cell(0, 5, (log.resulting_hash or "")[:32], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Footer ───────────────────────────────────────────────────────────────
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, f"Generated by ACPIA v1.0 | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | SRCAS Hackathon 2024", align="C")

    return bytes(pdf.output())


def _section_header(pdf, title: str):
    """Draw a styled section header."""
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, f"  {title}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(15, 23, 42)
    pdf.ln(2)
