"""veritas_schema

Revision ID: 122710bbf58b
Revises: 
Create Date: 2026-08-14 19:23:03.965378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '122710bbf58b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contradictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('caveat', sa.String(), nullable=False),
    sa.Column('source_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('judged_by', sa.Uuid(), nullable=True),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'proposed') = (judged_by IS NULL)", name='ck_contradiction_judge_consistency'),
    sa.CheckConstraint("severity IN ('high', 'medium', 'low')", name='ck_contradiction_severity'),
    sa.CheckConstraint("status IN ('proposed', 'confirmed_material', 'dismissed')", name='ck_contradiction_status'),
    sa.CheckConstraint('cardinality(source_ids) > 0', name='ck_contradiction_has_sources'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cosign_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'executed')", name='ck_cosign_status'),
    sa.CheckConstraint('requested_by IS DISTINCT FROM approved_by', name='ck_cosign_distinct_actors'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairing_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('dispute_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('scope_summary', sa.String(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('complainant', 'respondent')", name='ck_dispute_role'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['sealed_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('cases', sa.Column('case_type', sa.String(), nullable=False, server_default='guard'))
    op.add_column('custody_log', sa.Column('prev_hash', sa.String(length=64), nullable=False, server_default='0' * 64))
    op.add_column('custody_log', sa.Column('entry_hash', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('evidence', sa.Column('submitter_role', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence', sa.Column('authenticity_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('sealed_reports', sa.Column('claimed_when', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sealed_reports', 'claimed_when')
    op.drop_column('evidence', 'authenticity_indicators')
    op.drop_column('evidence', 'claimed_at')
    op.drop_column('evidence', 'submitter_role')
    op.drop_column('custody_log', 'entry_hash')
    op.drop_column('custody_log', 'prev_hash')
    op.drop_column('cases', 'case_type')
    op.drop_table('dispute_codes')
    op.drop_table('pairing_tokens')
    op.drop_table('cosign_requests')
    op.drop_table('contradictions')
    # ### end Alembic commands ###
