"""seal_claimed_by_set_null

Revision ID: f4a7b8e1f797
Revises: 122710bbf58b
Create Date: 2026-08-14 19:44:40.834238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a7b8e1f797'
down_revision: Union[str, None] = '122710bbf58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sealed_reports_claimed_by_fkey'), 'sealed_reports', type_='foreignkey')
    op.create_foreign_key(None, 'sealed_reports', 'cases', ['claimed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sealed_reports', type_='foreignkey')
    op.create_foreign_key(op.f('sealed_reports_claimed_by_fkey'), 'sealed_reports', 'cases', ['claimed_by'], ['id'])
    # ### end Alembic commands ###
