"""
Agent 8 — Case Synthesis & XAI
Correlates all agent outputs, detects contradictions, computes final risk scores,
prioritizes leads, and generates the evidence-citation chain for the case report.
"""
import json
import structlog
from typing import Optional
from tools.nlp_tool import query_llm
from app.config import settings

logger = structlog.get_logger(__name__)


class CaseSynthesisAgent:
    """
    Layer 5 — Intelligence Synthesis & Explainable AI.
    Runs AFTER all 7 specialist agents have completed.
    """
    AGENT_NAME = "case_synthesis"

    async def run(self, state: dict) -> dict:
        case_id = state["case_id"]
        all_leads = state.get("leads", [])
        agent_results = state.get("agent_results", [])
        errors = state.get("errors", [])

        progress_cb = state.get("progress_callback")
        if progress_cb:
            progress_cb({
                "type": "agent_update",
                "agent": self.AGENT_NAME,
                "status": "synthesizing",
                "progress": 85,
                "message": f"Synthesizing {len(all_leads)} leads from {len(agent_results)} agents...",
            })

        if not all_leads:
            return {
                **state,
                "synthesis": {
                    "total_leads": 0,
                    "high_risk_count": 0,
                    "summary": "No leads generated by specialist agents.",
                },
            }

        # 1. Cross-agent correlation: detect duplicate/contradictory leads
        deduplicated_leads = self._deduplicate_leads(all_leads)

        # 2. Detect contradictions
        contradictions = self._detect_contradictions(deduplicated_leads, agent_results)

        # 3. Compute aggregate risk profile
        risk_profile = self._compute_risk_profile(deduplicated_leads)

        # 4. Prioritize leads by risk score × confidence
        prioritized = sorted(
            deduplicated_leads,
            key=lambda l: float(l.get("risk_score", 0)) * float(l.get("confidence_upper", 50)) / 100,
            reverse=True,
        )
        for i, lead in enumerate(prioritized):
            lead["priority_rank"] = i + 1

        # 5. Generate case summary via LLM
        case_summary = self._generate_case_summary(prioritized[:10], agent_results, risk_profile)

        synthesis = {
            "total_leads": len(deduplicated_leads),
            "high_risk_count": sum(1 for l in deduplicated_leads if float(l.get("risk_score", 0)) >= 70),
            "medium_risk_count": sum(1 for l in deduplicated_leads if 40 <= float(l.get("risk_score", 0)) < 70),
            "agent_summary": {
                r.get("agent"): {"status": r.get("status"), "findings": r.get("findings_count", 0)}
                for r in agent_results
            },
            "contradictions": contradictions,
            "risk_profile": risk_profile,
            "case_summary": case_summary,
            "errors": errors,
        }

        return {
            **state,
            "leads": prioritized,  # Replace with prioritized version
            "agent_results": [{"agent": self.AGENT_NAME, "status": "completed", "findings_count": len(prioritized)}],
            "synthesis": synthesis,
        }

    def _deduplicate_leads(self, leads: list) -> list:
        """Remove near-duplicate leads (same evidence, very similar risk scores)."""
        seen = {}
        unique = []
        for lead in leads:
            # Create dedup key from evidence IDs and lead type
            citations = lead.get("evidence_citations", [])
            ev_ids = frozenset(c.get("evidence_id", "") for c in citations)
            key = (lead.get("lead_type", ""), ev_ids)

            if key not in seen:
                seen[key] = True
                unique.append(lead)

        return unique

    def _detect_contradictions(self, leads: list, agent_results: list) -> list:
        """Detect cases where different agents produced contradictory findings."""
        contradictions = []

        # Group leads by evidence ID
        by_evidence = {}
        for lead in leads:
            for citation in lead.get("evidence_citations", []):
                eid = citation.get("evidence_id")
                if eid:
                    by_evidence.setdefault(eid, []).append(lead)

        # Check for contradictions (e.g., one agent says high risk, another says low for same evidence)
        for eid, ev_leads in by_evidence.items():
            if len(ev_leads) > 1:
                scores = [float(l.get("risk_score", 0)) for l in ev_leads]
                if max(scores) - min(scores) > 40:
                    contradictions.append({
                        "evidence_id": eid,
                        "agents": [l.get("agent") for l in ev_leads],
                        "scores": scores,
                        "note": "Significant disagreement between agents on risk assessment for this evidence item",
                    })

        return contradictions

    def _compute_risk_profile(self, leads: list) -> dict:
        if not leads:
            return {"overall_risk": 0, "distribution": {}}

        scores = [float(l.get("risk_score", 0)) for l in leads]
        overall = max(scores) * 0.5 + (sum(scores) / len(scores)) * 0.5

        return {
            "overall_risk": round(overall, 2),
            "max_score": max(scores),
            "avg_score": round(sum(scores) / len(scores), 2),
            "distribution": {
                "critical_90_100": sum(1 for s in scores if s >= 90),
                "high_70_90": sum(1 for s in scores if 70 <= s < 90),
                "medium_40_70": sum(1 for s in scores if 40 <= s < 70),
                "low_0_40": sum(1 for s in scores if s < 40),
            },
        }

    def _generate_case_summary(self, top_leads: list, agent_results: list, risk_profile: dict) -> str:
        """Generate a human-readable case summary via LLM."""
        agents_summary = [
            f"- {r.get('agent', 'unknown')}: {r.get('status', 'unknown')} ({r.get('findings_count', 0)} findings)"
            for r in agent_results
        ]

        leads_summary = [
            f"- [{l.get('lead_type', 'unknown')}] Risk: {l.get('risk_score', 0):.0f}/100 — {l.get('summary', '')[:200]}"
            for l in top_leads[:5]
        ]

        prompt = f"""You are a forensic case analyst assistant. Summarize these investigation findings for an investigator.

Agent Analysis Summary:
{chr(10).join(agents_summary)}

Risk Profile:
- Overall Risk Score: {risk_profile.get('overall_risk', 0):.0f}/100
- High Risk Leads: {risk_profile.get('distribution', {}).get('high_70_90', 0) + risk_profile.get('distribution', {}).get('critical_90_100', 0)}
- Total Leads: {sum(risk_profile.get('distribution', {}).values())}

Top Findings:
{chr(10).join(leads_summary)}

Write a professional 3-5 sentence case summary for an investigator. Be factual. Note that all findings are AI-generated leads requiring human verification. Do not make determinations of guilt or fact."""

        try:
            return query_llm(prompt, temperature=0.2, max_tokens=500)
        except Exception as e:
            logger.warning("Case summary generation failed", error=str(e))
            return f"Analysis complete. {len(top_leads)} leads generated across {len(agent_results)} specialist agents. Overall risk score: {risk_profile.get('overall_risk', 0):.0f}/100. All leads require investigator review."
